apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: mpi9b1j2w-go 
  janus-idp.io/tekton: mpi9b1j2w-go
  backstage.io/kubernetes-id: mpi9b1j2w-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: mpi9b1j2w-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  