apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: mpi9b1j2w-go-gitops
  description: This is GitOps manifest for mpi9b1j2w-go   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-name: mpi9b1j2w-go
    janus-idp.io/tekton: mpi9b1j2w-go
    backstage.io/kubernetes-id: mpi9b1j2w-go 
    backstage.io/techdocs-ref: dir:. 
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:mpi9b1j2w-go
