apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: mpi9b1j2w-go
  janus-idp.io/tekton: mpi9b1j2w-go
  backstage.io/kubernetes-id: mpi9b1j2w-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: mpi9b1j2w-go
resources:
- deployment.yaml
- route.yaml
- service.yaml
