apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: mpi9b1j2w-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: mpi9b1j2w-go 
  name: mpi9b1j2w-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: mpi9b1j2w-go 
